services:
  # -------------------------------
  # 1. BASE DE DATOS (mariadba4)
  # -------------------------------
  mariadb:
    image: mariadb:latest
    container_name: mariadba4
    restart: unless-stopped
    environment:
      # Credenciales Root
      MYSQL_ROOT_PASSWORD: root
      # Nombre de la BDD que se creará automáticamente
      MYSQL_DATABASE: Pescaderia
    volumes:
      - mariadb-dataa4:/var/lib/mysql
      # Carga automática del script SQL al iniciar
      - ./Pescados.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  # -------------------------------
  # 2. PHPMYADMIN (Herramienta BDD)
  # -------------------------------
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmina4
    restart: unless-stopped
    environment:
      PMA_HOST: mariadba4
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "7004:80"
    depends_on:
      - mariadb

  # -------------------------------
  # 3. PYTHON API (Puerto 9090)
  # -------------------------------
  python:
    build: ./api
    container_name: pythona4
    restart: unless-stopped
    environment:
      # Configuración de Flask
      PORT: 5000       # El puerto INTERNO sigue siendo 5000
      HOST: 0.0.0.0
      
      # VARIABLES PARA CONEXIÓN BDD (Coinciden con bd.py)
      DB_HOST: mariadba4
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: Pescaderia
    ports:
      # AQUI ESTÁ EL CAMBIO: Tu PC (9090) -> Contenedor (5000)
      - "9090:5000"
    depends_on:
      - mariadb

  # -------------------------------
  # 4. APACHE/PHP (Puerto 9093)
  # -------------------------------
  apache-waf:
    build: ./apache
    container_name: apachea4
    restart: unless-stopped
    ports:
      # AQUI ESTÁ EL CAMBIO: Tu PC (9093) -> Contenedor (80)
      - "9093:80"
    depends_on:
      - python

volumes:
  mariadb-dataa4:
