apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: grupoa4
type: Opaque
stringData:
  # Contraseñas definidas en tu código/sql
  root_password: "example"   
  db_user: "root"
  db_password: "example"
  db_name: "ciber"