apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: grupoa4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: python
        image: grupo4a/python-grupoa4:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000          # CAMBIADO: Antes 8080
        env:
        - name: DB_HOST
          value: "mariadba4"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_name
---
apiVersion: v1
kind: Service
metadata:
  name: pythona4 
  namespace: grupoa4
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 8080         # El puerto que ve Apache (se mantiene igual)
      targetPort: 5000   # El puerto real del contenedor (CAMBIADO)
